name: Setup easy-setup
description: Download, install, and setup easy-setup to your path.
author: ahaoboy
branding:
  icon: play-circle
  color: white
inputs:
  url:
    description: 'The url to install'
    required: true

runs:
  using: "composite"
  steps:
    - name: Run installer
      shell: bash
      run: |
        curl -fsSL https://raw.githubusercontent.com/easy-install/easy-install/main/install.sh | bash

    - name: Run installer
      shell: bash
      run: |
        bash "${{ github.action_path }}/action.sh"
      env:
        INPUT_URL: ${{ inputs.url }}